import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Token from '../../components/accessToken'
import { Box, Paper, Typography } from '@mui/material'
import ResponsiveAppBar from '../../components/appBar'
import LoginBtn from '../../components/login-button'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar/>
      <Box alignItems={"center"} textAlign={"center"} minHeight={"100vh"}display={"flex"}  >
        <Box>
      {/* <Paper elevation={4}> */}
        <Typography>Next.js + NextAuth.js</Typography>
        <LoginBtn/>
      {/* </Paper> */}

        </Box>
        
      </Box>     

      <Token/>
    </>
  )
}
